version: "3"
services:
  achievement:
    build:
      context: .
    volumes:
      - ./:/go/src/github.com/nigoroku/amb-achievement
    ports:
      - "8083:8083"
    environment:
      - DATABASE_HOST=amb-db
      - DATABASE_PASSWORD=base0210
      - DATABASE=ambitious
      - DATABASE_USERNAME=root
    tty: true
    stdin_open: true
    networks:
      - amb-network

networks:
  amb-network:
    external: true
